# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bfd_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import sdk_common_pb2 as sdk__common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='bfd_service.proto',
  package='srlinux.sdk',
  syntax='proto3',
  serialized_options=b'Z\034nokia.com/srlinux/sdk/protos',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x62\x66\x64_service.proto\x12\x0bsrlinux.sdk\x1a\x10sdk_common.proto\"T\n\x1d\x42\x66\x64SessionSubscriptionRequest\x12\x33\n\x03key\x18\x01 \x01(\x0b\x32&.srlinux.sdk.BfdmgrGeneralSessionKeyPb\"\x9b\x02\n\x19\x42\x66\x64mgrGeneralSessionKeyPb\x12-\n\x0bsrc_ip_addr\x18\x01 \x01(\x0b\x32\x18.srlinux.sdk.IpAddressPb\x12-\n\x0b\x64st_ip_addr\x18\x02 \x01(\x0b\x32\x18.srlinux.sdk.IpAddressPb\x12\x13\n\x0binstance_id\x18\x03 \x01(\r\x12\x46\n\x04type\x18\x04 \x01(\x0e\x32\x38.srlinux.sdk.BfdmgrGeneralSessionKeyPb.BfdmgrSessionType\"C\n\x11\x42\x66\x64mgrSessionType\x12\x18\n\x14SESSION_TYPE_UNKNOWN\x10\x00\x12\x14\n\x10SESSION_TYPE_P2P\x10\x01\"\x93\x03\n\x1a\x42\x66\x64mgrGeneralSessionDataPb\x12K\n\x06status\x18\x01 \x01(\x0e\x32;.srlinux.sdk.BfdmgrGeneralSessionDataPb.BfdmgrSessionStatus\x12N\n\x08sub_type\x18\x02 \x01(\x0e\x32<.srlinux.sdk.BfdmgrGeneralSessionDataPb.BfdmgrSessionSubType\x12\x11\n\tsrc_if_id\x18\x03 \x01(\r\"u\n\x14\x42\x66\x64mgrSessionSubType\x12\x1c\n\x18SESSION_SUB_TYPE_UNKNOWN\x10\x00\x12\x1f\n\x1bSESSION_SUB_TYPE_SINGLE_HOP\x10\x01\x12\x1e\n\x1aSESSION_SUB_TYPE_MULTI_HOP\x10\x02\"N\n\x13\x42\x66\x64mgrSessionStatus\x12\x0b\n\x07INVALID\x10\x00\x12\x0e\n\nADMIN_DOWN\x10\x01\x12\x08\n\x04\x44OWN\x10\x02\x12\x08\n\x04INIT\x10\x03\x12\x06\n\x02UP\x10\x04\"\xae\x01\n\x16\x42\x66\x64SessionNotification\x12(\n\x02op\x18\x01 \x01(\x0e\x32\x1c.srlinux.sdk.SdkMgrOperation\x12\x33\n\x03key\x18\x02 \x01(\x0b\x32&.srlinux.sdk.BfdmgrGeneralSessionKeyPb\x12\x35\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\'.srlinux.sdk.BfdmgrGeneralSessionDataPbB\x1eZ\x1cnokia.com/srlinux/sdk/protosb\x06proto3'
  ,
  dependencies=[sdk__common__pb2.DESCRIPTOR,])



_BFDMGRGENERALSESSIONKEYPB_BFDMGRSESSIONTYPE = _descriptor.EnumDescriptor(
  name='BfdmgrSessionType',
  full_name='srlinux.sdk.BfdmgrGeneralSessionKeyPb.BfdmgrSessionType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SESSION_TYPE_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SESSION_TYPE_P2P', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=355,
  serialized_end=422,
)
_sym_db.RegisterEnumDescriptor(_BFDMGRGENERALSESSIONKEYPB_BFDMGRSESSIONTYPE)

_BFDMGRGENERALSESSIONDATAPB_BFDMGRSESSIONSUBTYPE = _descriptor.EnumDescriptor(
  name='BfdmgrSessionSubType',
  full_name='srlinux.sdk.BfdmgrGeneralSessionDataPb.BfdmgrSessionSubType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SESSION_SUB_TYPE_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SESSION_SUB_TYPE_SINGLE_HOP', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SESSION_SUB_TYPE_MULTI_HOP', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=631,
  serialized_end=748,
)
_sym_db.RegisterEnumDescriptor(_BFDMGRGENERALSESSIONDATAPB_BFDMGRSESSIONSUBTYPE)

_BFDMGRGENERALSESSIONDATAPB_BFDMGRSESSIONSTATUS = _descriptor.EnumDescriptor(
  name='BfdmgrSessionStatus',
  full_name='srlinux.sdk.BfdmgrGeneralSessionDataPb.BfdmgrSessionStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INVALID', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ADMIN_DOWN', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DOWN', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INIT', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UP', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=750,
  serialized_end=828,
)
_sym_db.RegisterEnumDescriptor(_BFDMGRGENERALSESSIONDATAPB_BFDMGRSESSIONSTATUS)


_BFDSESSIONSUBSCRIPTIONREQUEST = _descriptor.Descriptor(
  name='BfdSessionSubscriptionRequest',
  full_name='srlinux.sdk.BfdSessionSubscriptionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='srlinux.sdk.BfdSessionSubscriptionRequest.key', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=136,
)


_BFDMGRGENERALSESSIONKEYPB = _descriptor.Descriptor(
  name='BfdmgrGeneralSessionKeyPb',
  full_name='srlinux.sdk.BfdmgrGeneralSessionKeyPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='src_ip_addr', full_name='srlinux.sdk.BfdmgrGeneralSessionKeyPb.src_ip_addr', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dst_ip_addr', full_name='srlinux.sdk.BfdmgrGeneralSessionKeyPb.dst_ip_addr', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='instance_id', full_name='srlinux.sdk.BfdmgrGeneralSessionKeyPb.instance_id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='srlinux.sdk.BfdmgrGeneralSessionKeyPb.type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _BFDMGRGENERALSESSIONKEYPB_BFDMGRSESSIONTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=422,
)


_BFDMGRGENERALSESSIONDATAPB = _descriptor.Descriptor(
  name='BfdmgrGeneralSessionDataPb',
  full_name='srlinux.sdk.BfdmgrGeneralSessionDataPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='srlinux.sdk.BfdmgrGeneralSessionDataPb.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sub_type', full_name='srlinux.sdk.BfdmgrGeneralSessionDataPb.sub_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='src_if_id', full_name='srlinux.sdk.BfdmgrGeneralSessionDataPb.src_if_id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _BFDMGRGENERALSESSIONDATAPB_BFDMGRSESSIONSUBTYPE,
    _BFDMGRGENERALSESSIONDATAPB_BFDMGRSESSIONSTATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=425,
  serialized_end=828,
)


_BFDSESSIONNOTIFICATION = _descriptor.Descriptor(
  name='BfdSessionNotification',
  full_name='srlinux.sdk.BfdSessionNotification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='op', full_name='srlinux.sdk.BfdSessionNotification.op', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key', full_name='srlinux.sdk.BfdSessionNotification.key', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='srlinux.sdk.BfdSessionNotification.data', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=831,
  serialized_end=1005,
)

_BFDSESSIONSUBSCRIPTIONREQUEST.fields_by_name['key'].message_type = _BFDMGRGENERALSESSIONKEYPB
_BFDMGRGENERALSESSIONKEYPB.fields_by_name['src_ip_addr'].message_type = sdk__common__pb2._IPADDRESSPB
_BFDMGRGENERALSESSIONKEYPB.fields_by_name['dst_ip_addr'].message_type = sdk__common__pb2._IPADDRESSPB
_BFDMGRGENERALSESSIONKEYPB.fields_by_name['type'].enum_type = _BFDMGRGENERALSESSIONKEYPB_BFDMGRSESSIONTYPE
_BFDMGRGENERALSESSIONKEYPB_BFDMGRSESSIONTYPE.containing_type = _BFDMGRGENERALSESSIONKEYPB
_BFDMGRGENERALSESSIONDATAPB.fields_by_name['status'].enum_type = _BFDMGRGENERALSESSIONDATAPB_BFDMGRSESSIONSTATUS
_BFDMGRGENERALSESSIONDATAPB.fields_by_name['sub_type'].enum_type = _BFDMGRGENERALSESSIONDATAPB_BFDMGRSESSIONSUBTYPE
_BFDMGRGENERALSESSIONDATAPB_BFDMGRSESSIONSUBTYPE.containing_type = _BFDMGRGENERALSESSIONDATAPB
_BFDMGRGENERALSESSIONDATAPB_BFDMGRSESSIONSTATUS.containing_type = _BFDMGRGENERALSESSIONDATAPB
_BFDSESSIONNOTIFICATION.fields_by_name['op'].enum_type = sdk__common__pb2._SDKMGROPERATION
_BFDSESSIONNOTIFICATION.fields_by_name['key'].message_type = _BFDMGRGENERALSESSIONKEYPB
_BFDSESSIONNOTIFICATION.fields_by_name['data'].message_type = _BFDMGRGENERALSESSIONDATAPB
DESCRIPTOR.message_types_by_name['BfdSessionSubscriptionRequest'] = _BFDSESSIONSUBSCRIPTIONREQUEST
DESCRIPTOR.message_types_by_name['BfdmgrGeneralSessionKeyPb'] = _BFDMGRGENERALSESSIONKEYPB
DESCRIPTOR.message_types_by_name['BfdmgrGeneralSessionDataPb'] = _BFDMGRGENERALSESSIONDATAPB
DESCRIPTOR.message_types_by_name['BfdSessionNotification'] = _BFDSESSIONNOTIFICATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BfdSessionSubscriptionRequest = _reflection.GeneratedProtocolMessageType('BfdSessionSubscriptionRequest', (_message.Message,), {
  'DESCRIPTOR' : _BFDSESSIONSUBSCRIPTIONREQUEST,
  '__module__' : 'bfd_service_pb2'
  # @@protoc_insertion_point(class_scope:srlinux.sdk.BfdSessionSubscriptionRequest)
  })
_sym_db.RegisterMessage(BfdSessionSubscriptionRequest)

BfdmgrGeneralSessionKeyPb = _reflection.GeneratedProtocolMessageType('BfdmgrGeneralSessionKeyPb', (_message.Message,), {
  'DESCRIPTOR' : _BFDMGRGENERALSESSIONKEYPB,
  '__module__' : 'bfd_service_pb2'
  # @@protoc_insertion_point(class_scope:srlinux.sdk.BfdmgrGeneralSessionKeyPb)
  })
_sym_db.RegisterMessage(BfdmgrGeneralSessionKeyPb)

BfdmgrGeneralSessionDataPb = _reflection.GeneratedProtocolMessageType('BfdmgrGeneralSessionDataPb', (_message.Message,), {
  'DESCRIPTOR' : _BFDMGRGENERALSESSIONDATAPB,
  '__module__' : 'bfd_service_pb2'
  # @@protoc_insertion_point(class_scope:srlinux.sdk.BfdmgrGeneralSessionDataPb)
  })
_sym_db.RegisterMessage(BfdmgrGeneralSessionDataPb)

BfdSessionNotification = _reflection.GeneratedProtocolMessageType('BfdSessionNotification', (_message.Message,), {
  'DESCRIPTOR' : _BFDSESSIONNOTIFICATION,
  '__module__' : 'bfd_service_pb2'
  # @@protoc_insertion_point(class_scope:srlinux.sdk.BfdSessionNotification)
  })
_sym_db.RegisterMessage(BfdSessionNotification)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
